application: sample-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: api.appl.application
- url: /js
  static_dir: htdocs/js
- url: /css
  static_dir: htdocs/css
- url: /
  static_files: htdocs/index.html
  upload: htdocs/index.html
  
